### ISSUE TITLE
0.17.0 breaks socks support in Electrum

### ISSUE THREAD

**Issue by nomnombtc** [kyuupichan/aiorpcX#17]
Hello,

I know Electrum "officially" only supports 'aiorpcx>=0.9,<0.11',
but some distros / user repositories ship newer version anyway, like for example
Arch Linux currently lists aiorpcX 0.16.1 as dependency for Electrum.

It works fine as far as I can tell up to 0.16.2, so some of the socks proxy
related changes in the 0.17.0 release seems to cause this error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/electrum/util.py", line 910, in wrapper
    return await func(*args, **kwargs)
  File "/usr/lib64/python3.7/site-packages/electrum/network.py", line 711, in _run_new_interface
    interface = Interface(self, server, self.proxy)
  File "/usr/lib64/python3.7/site-packages/electrum/interface.py", line 188, in __init__
    self._set_proxy(proxy)
  File "/usr/lib64/python3.7/site-packages/electrum/interface.py", line 214, in _set_proxy
    self.proxy = aiorpcx.socks.SOCKSProxy((proxy['host'], int(proxy['port'])), aiorpcx.socks.SOCKS5, auth)
  File "/usr/lib64/python3.7/site-packages/aiorpcx/socks.py", line 270, in __init__
    address = NetAddress.from_string(address)
  File "/usr/lib64/python3.7/site-packages/aiorpcx/util.py", line 144, in from_string
    raise TypeError(f'address must be a string: {string}')
TypeError: address must be a string: ('127.0.0.1', 9150)
```
Sorry if this is intended behavior and something in Electrum needs to be adapted.

**Comment by kyuupichan** [comment]
It's intended.  aiorpcX doesn't have a stable API; Electrum needs to specify which version it needs
