### ISSUE TITLE
Exception from user division by zero average response time

### ISSUE THREAD

**Issue by rt121212121** [kyuupichan/aiorpcX#29]
This is with latest ElectrumSV master. Haven't seen it myself. 
```
2019-11-19 12:05:19,324:ERROR:async:async task raised an unhandled exception

Traceback (most recent call last):

  File "C:\ZZZZ\electrumsv\electrumsv\network.py", line 1254, in _maintain_wallet

    await group.spawn(wallet.synchronize_loop)

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 242, in __aexit__

    await self.join()

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 195, in join

    task = await self.next_done()

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 161, in next_done

    await self._done_event.wait()

  File "C:\Python37\lib\asyncio\locks.py", line 293, in wait

    await fut

concurrent.futures._base.CancelledError

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\ZZZZ\electrumsv\electrumsv\async_.py", line 93, in _collect

    future.result()

  File "C:\Python37\lib\concurrent\futures\_base.py", line 425, in result

    return self.__get_result()

  File "C:\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result

    raise self._exception

  File "C:\ZZZZ\electrumsv\electrumsv\network.py", line 948, in _main_task

    await group.spawn(self._monitor_wallets, group)

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 242, in __aexit__

    await self.join()

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 208, in join

    await self.cancel_remaining()

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 221, in cancel_remaining

    await task

  File "C:\ZZZZ\electrumsv\electrumsv\network.py", line 1261, in _maintain_wallet

    await SVSession.unsubscribe_wallet(wallet, self.main_session())

  File "C:\ZZZZ\electrumsv\electrumsv\network.py", line 904, in unsubscribe_wallet

    await group.spawn(session._unsubscribe_from_script_hash(script_hash))

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 242, in __aexit__

    await self.join()

  File "C:\Python37\lib\site-packages\aiorpcx\curio.py", line 211, in join

    raise task.exception()

  File "C:\ZZZZ\electrumsv\electrumsv\network.py", line 609, in _unsubscribe_from_script_hash

    return await self.send_request(SCRIPTHASH_UNSUBSCRIBE, [script_hash])

  File "C:\Python37\lib\site-packages\aiorpcx\session.py", line 525, in send_request

    return await self._send_concurrent(message, future, 1)

  File "C:\Python37\lib\site-packages\aiorpcx\session.py", line 503, in _send_concurrent

    self._recalc_concurrency()

  File "C:\Python37\lib\site-packages\aiorpcx\session.py", line 423, in _recalc_concurrency

    target = int(0.5 + max(floor, min(cap, current * self.target_response_time / avg)))

ZeroDivisionError: float division by zero
```

**Comment by SomberNight** [comment]
same as https://github.com/kyuupichan/aiorpcX/issues/26 ?

**Comment by kyuupichan** [comment]
Yes @SomberNight fixed this I believe; I should do a release.  I'll try and get that done in the next 24 hours.
